services:
  
  submit-app:
    build:
      context: ./submit-app
    container_name: submit-app
    restart: always
    env_file:
      - .env
    ports:
      - "${SUBMIT_CONTAINER_PORT}:${SUBMIT_PORT}"
